### ISSUE TITLE
`map` and `map --camel` corrupts `previewFeature: "multiSchema"`

### ISSUE THREAD

**Issue by dox-op** [RaresAil/prisma-mapper#17]
_I must put a premise, this is my first ever issue open on GitHub_

I'm having troubles using this dependency with following configurations
`generator client {
  provider        = "prisma-client-js"
  previewFeatures = ["multiSchema"]
}` 
[Prisma documentation](https://www.prisma.io/docs/guides/database/multi-schema#how-to-include-multiple-database-schemas-in-your-prisma-schema)

If I run `npx prisma db pull --force && npx prisma-mapper map --camel && npx prisma generate`
The consequence is that my configuration for multiple schemas is gone:

`datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}`

leaving on every 

`model ... { ... 
  @@schema
}` empty

All of this happens also using a `prisma-mapper.json` and run `npx prisma db pull --force && npx prisma-mapper map && npx prisma generate`

**Comment by RaresAil** [comment]
Hey, thank you for reporting this issue, i will investigate it

**Comment by RaresAil** [comment]
@imdoxy The issue is fixed in 1.3.3
