### ISSUE TITLE
`prisma-mapper map` doesn't respect data type in fields while setting defaults

### ISSUE THREAD

**Issue by dox-op** [RaresAil/prisma-mapper#20]
_System information_:
* **NodeJS** 18.15.0
* **npm** 9.5.0
* **prisma-mapper** 1.3.3

***
Hi!
following is an image of a `column` in database

![image](https://user-images.githubusercontent.com/6050950/226420611-2b4ad86e-f2e3-42d0-a375-ef5b35b1c223.png)

this is how the `prisma-mapper map` translated the default value
`TableName { [...] column BigInt?   @default("-2") [...] }`

and `prisma generate` can't validate the resulting `schema.prisma`

**Comment by RaresAil** [comment]
I don't see an issue in the table, BigInt is an alias for int8

EDIT: Can you provide the steps on how you get there? Did you did an introspection or?

@imdoxy

**Comment by RaresAil** [comment]
Found the issue, prisma internals was telling that negatives numbers were strings instead of ints, it will be fixed in `1.4.1` @imdoxy

**Comment by dox-op** [comment]
Thanks!
